### ISSUE TITLE
Upgrade to Cyrus IMAP v3.1.9

### ISSUE THREAD

**Issue by marclaporte** [chmanie/hemhem#1]
Please: https://github.com/cyrusimap/cyrus-imapd/releases/tag/cyrus-imapd-3.1.9

We need to test extensively before 3.2 is released: https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2020-January/004566.html

More info: https://wikisuite.org/JMAP

Thanks!

**Comment by stephenstubbs** [comment]
That would help me a lot too if you could upgrade it to 3.1.9

**Comment by chmanie** [comment]
Sure, I can look into it! I hope it won't require too many adjustments

**Comment by chmanie** [comment]
Okay I pushed a working dockerfile with v3.1.9
