### ISSUE TITLE
Postgres PAM Support in Saslauthd

### ISSUE THREAD

**Issue by stephenstubbs** [chmanie/hemhem#2]
Hi,

I'm creating a kubernetes operator based on this brilliant project. We using postgres not mysql so I'm forking it for now just to add postgres support. Will do a pr once done and it would be great if that could be included.

**Comment by stephenstubbs** [comment]
These two pull requests are regarding postgres https://github.com/chmanie/hemhem/pull/3 https://github.com/chmanie/hemhem/pull/4. I understand though if you don't want to increase the container sizes to support postgres.

**Comment by stephenstubbs** [comment]
For the time being I've just created a postfix and saslauthd container with those changes and removed the scripts from them as they will be injected by kubernetes. I will still use your cyrus imap container as that doesn't need direct access to the db.

**Comment by chmanie** [comment]
This should be done with #3 and #4, right?

**Comment by stephenstubbs** [comment]
Yes thats done thank you very much. I'll delete my fork and the dockerhub containers so we stay consistent.

**Comment by chmanie** [comment]
I added you as a collaborator, so feel free to open PRs without forking :)

**Comment by stephenstubbs** [comment]
Ok brilliant thanks. I should have the operator done tomorrow. I'll add you as a collaborator there just in case you need a kubernetes deployment at any point.
